apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node-app

spec:
  containers:
    - name: node-container
      image: darshif5/simple-node-app:node-app-test-new
      ports:
        - containerPort: 8000
