apiVersion: v1
kind: Pod
metadata:
  name: node-pod
  namespace: node155

spec:
  containers:
    - name: node-container
      image: darshif5/simple-node-app:node-todo
      ports:
        - containerPort: 8000
