apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: node-app-replica-set
  namespace: node155
  labels:
    app: guestbook
    tier: node-label
spec:
  # modify replicas according to your case
  replicas: 6
  selector:
    matchLabels:
      tier: node-label
  template:
    metadata:
      namespace: node155
      labels:
        tier: node-label
    spec:
      containers:
      - name: node-container-rep
        image: darshif5/simple-node-app:node-todo
